# Generated by Django 5.1.1 on 2024-10-10 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ttc',
        ),
        migrations.CreateModel(
            name='ProductFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix unitaire HT')),
                ('price_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix unitaire TTC')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.fournisseur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.product')),
            ],
            options={
                'verbose_name': 'ProduitFournisseur',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandeName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('etatCommande', models.SmallIntegerField(choices=[(0, 'Preaparing'), (1, 'Done'), (2, 'Received')], default=0)),
                ('produitFournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.productfournisseur')),
            ],
            options={
                'verbose_name': 'Commande',
            },
        ),
    ]
